---
# =======================
# Paths to required files
# =======================

lut_path: /home/taylor/Documents/ar40-aug15/monte_carlo/LUT.h5
#xcfg_root: /mnt/home/jbradt/Documents/Data/e15503b/configs
#xcfg_path: run_0077/configure-e15503b.xcfg
padmap_path: /home/taylor/Documents/independent-research/event-gen/Lookup20150611.csv
beampads_path: /home/taylor/Documents/ar40-aug15/notebooks/beampads.txt
#runtables_path: /mnt/home/jbradt/Documents/Data/e15503b/e15503b-rundata-parseable.csv
pedestals_path: /home/taylor/Documents/independent-research/event-gen/Pedestals20150810.csv

# ===================
# Detector conditions
# ===================

tilt: 6.2  # in degrees
#tilt: 0.0  # in degrees
pad_rot_angle: -108  # in degrees

# vdmag: -5.2  # drift velocity magnitude in cm/us
vd: [-0.0603573 , -0.55178666, -5.14005679]  # in cm/us, in the detector frame
#vd: [ 0. , 0. , -5.2]  # in cm/us, in the detector frame

# efieldMag: 9500  #V/m
efield: [    0.        , -1025.99387921,  9444.43415774]  # in SI units, in the uvw/lab frame
#efield:  [ 0. , 0. , 9500.]  # in SI units, in the uvw/lab frame
bfield: [ 0.  ,  0.  ,  1.68]  # in Tesla, in the uvw/lab frame
# bfield_correction: 1.76

gas_name: 'isobutane'
gas_pressure: 19.2  # torr
ioniz: 23.0  # eV
diffusion_sigma: 0.1e-3  # standard deviation of electron diffusion distribution, in m
evtgen_diffusion_sigma: 0.1e-4  # use a smaller value when simulating events

# ======================
# Electronics parameters
# ======================

clock: 12.5    # MHz
shape: 280e-9  # s
pad_thresh_MSB: 1  # "GlobalThresholdValue"
pad_thresh_LSB: 2  # "LSBThresholdValue"
trigger_signal_width: 235e-9  # in seconds. Controlled by "isTOTActive" and "isTriggerWidth200ns" in Reg1
multiplicity_threshold: 20000
multiplicity_window: 300  # number of periods of 25 MHz clock. "multWindowSize"
electronics_gain: 120e-15  # in coulombs
trigger_discriminator_fraction: 0.175  # as a decimal, not a percent
micromegas_gain: 500

# ===================
# Particle parameters
# ===================

beam_mass: 46
beam_charge: 18
beam_enu0: 4.17  # (4.6*46 - 20) / 46, MeV/u

mass_num: 1  # for the scattered particle
charge_num: 1

tracker_max_en: 100  # MeV, integer. The total kinetic energy cutoff for the tracker's energy loss lookup table

# ==================
# Fitting parameters
# ==================

# beam_center: [   0.  , -115.  ,  224.64]  # mm
micromegas_tb: 38  # Time bucket corresponding to micromegas, from trigger. (Should be 52?)

# Monte Carlo settings
num_iters: 20
num_pts: 500
red_factor: 0.8
sigma:
    x: 0.1      # m
    y: 0.1      # m
    z: 0.1   # m
    enu: 4.0  # MeV/u
    azi: 60   # degrees
    pol: 30   # degrees


# ===================
# Cleaning parameters
# ===================

cleaning_config:
    linear_hough_max: 2000
    linear_hough_nbins: 500

    circle_hough_max: 500
    circle_hough_nbins: 200

    peak_width: 4

    max_distance_from_line: 40
    min_pts_per_line: 10
    min_num_neighbors: 1
    neighbor_radius: 15

    last_tb: 505  # Any time bucket after this will be dropped

# =================
# VME channel setup
# =================

vme_channels:
    adc:
      - mesh
      - ic
      - trig
    scalers:
      - cobo0
      - cobo1
      - cobo2
      - cobo3
      - cobo4
      - cobo5
      - cobo6
      - cobo7
      - cobo8
      - cobo9
      - cobo_or
      - busy_or
      - mesh
      - beam
      - ic_downscale
      - ic
      - free_trig
      - live_trig

# =====================
# Simulation parameters
# =====================

# Simulated distributions
dist_num_pts: 5000

noise_stddev: 6.0  # size of electronics noise distribution, in ADC bins
#noise_stddev: 1  # size of electronics noise distribution, in ADC bins
baseline_depression_scale: 40.0
big_pad_multiplier: 4

# Set these parameters to simulate beam dispersion
max_beam_angle: 2    # degrees
beam_origin_z: 1.14  # m


# =============
# Logging setup
# =============

logging_config:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: '[%(name)s.%(funcName)s] %(levelname)s: %(message)s'
    handlers:
        console:
            class: 'logging.StreamHandler'
            formatter: 'simple'
            level: 'INFO'
    root:
        level: 'INFO'
        handlers:
            - console
